table Dealers
	lineageTag: a1dbb3eb-7b08-cdf6-2f67-51f34c3a093a

	column DealerCode
		dataType: string
		lineageTag: 36818c05-1105-b7b2-01cd-9fcf9cb883d6
		summarizeBy: none
		sourceColumn: DealerCode

		annotation SummarizationSetBy = Automatic

	column DealerName
		dataType: string
		lineageTag: 0bba7258-0ccf-1bcb-0940-66895ccedc86
		summarizeBy: none
		sourceColumn: DealerName

		annotation SummarizationSetBy = Automatic

	column Area
		dataType: string
		lineageTag: fb7e2a44-1bf2-0d5d-9c87-fc1f708777fe
		summarizeBy: none
		sourceColumn: Area

		annotation SummarizationSetBy = Automatic

	column DealingSince
		dataType: int64
		formatString: 0
		lineageTag: c27b6b54-583c-d0d8-8562-12ae43c36d44
		summarizeBy: none
		sourceColumn: DealingSince

		annotation SummarizationSetBy = Automatic

	column CreditLimit
		dataType: int64
		formatString: #,0
		lineageTag: b9064560-eaca-835f-9086-927d99e57677
		summarizeBy: none
		sourceColumn: CreditLimit

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 2ba1cbba-82a5-8822-049c-5601a4e5e335
		summarizeBy: none
		sourceColumn: Segment
		sortByColumn: SegmentOrder

		annotation SummarizationSetBy = Automatic

	column SegmentOrder
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 22926c78-057f-9570-c9c9-8ba396d5dfd8
		summarizeBy: none
		sourceColumn: SegmentOrder

		annotation SummarizationSetBy = Automatic

	column RiskScore
		dataType: int64
		formatString: 0
		lineageTag: c5ec9580-bc24-7a9e-d93f-76dc1bcb9c86
		summarizeBy: none
		sourceColumn: RiskScore

		annotation SummarizationSetBy = Automatic

	column RiskBand
		dataType: string
		lineageTag: f28a19d4-e316-77f2-5534-bf473e55882f
		summarizeBy: none
		sourceColumn: RiskBand

		annotation SummarizationSetBy = Automatic

	column ProbLate60
		dataType: double
		formatString: 0.0%
		lineageTag: 1e1ada5f-934a-d25a-b604-7ba867a8d267
		summarizeBy: none
		sourceColumn: ProbLate60

		annotation SummarizationSetBy = Automatic

	partition Dealers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Dealers.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.TransformColumns(Promoted, List.Transform(Table.ColumnNames(Promoted), (c) => {c, each if _ = "" then null else _})),
				    Typed = Table.TransformColumnTypes(Blanks, {{"DealerCode", type text}, {"DealerName", type text}, {"Area", type text}, {"DealingSince", Int64.Type}, {"CreditLimit", Int64.Type}, {"Segment", type text}, {"SegmentOrder", Int64.Type}, {"RiskScore", Int64.Type}, {"RiskBand", type text}, {"ProbLate60", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

