table Products
	lineageTag: 068f80c7-519d-0528-fb08-e82137a72131

	column ModelCode
		dataType: string
		lineageTag: 910652e6-055b-0d39-f4d2-c028a7a73239
		summarizeBy: none
		sourceColumn: ModelCode

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c7b4a561-a7bb-2385-6fde-edb91ad37e5b
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 1024954a-8fa3-b85b-9893-0fd4cdf9fb0b
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: a069e585-deb4-944e-fabb-9a6d9032fcf0
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column DealerRate
		dataType: int64
		formatString: #,0
		lineageTag: 4a4a604c-119e-76b8-0cfa-d3ea24588a5b
		summarizeBy: none
		sourceColumn: DealerRate

		annotation SummarizationSetBy = Automatic

	column MarginPct
		dataType: double
		formatString: 0.0
		lineageTag: 1a3c8321-5073-1696-c0ff-269abd02e067
		summarizeBy: none
		sourceColumn: MarginPct

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Products.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Blanks = Table.TransformColumns(Promoted, List.Transform(Table.ColumnNames(Promoted), (c) => {c, each if _ = "" then null else _})),
				    Typed = Table.TransformColumnTypes(Blanks, {{"ModelCode", type text}, {"Category", type text}, {"Description", type text}, {"Size", type text}, {"DealerRate", Int64.Type}, {"MarginPct", type number}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table

